version: "3.8"

services:
  web:
    build: .
    container_name: free_mentors_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
